FROM node:22-alpine
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install --legacy-peer-deps

COPY libs/infra/tadil-database/package.json libs/infra/tadil-database/
RUN cd libs/infra/tadil-database && npm install --legacy-peer-deps

COPY libs/infra/file-storage/package.json libs/infra/file-storage/
RUN cd libs/infra/file-storage && npm install --legacy-peer-deps

COPY . .

RUN npm run db-generate
RUN npx nx build tadil-mobile-api --prod

COPY libs/infra/tadil-database/prisma ./libs/infra/tadil-database/prisma

ENV NODE_ENV=production
ENV PORT=4445

EXPOSE 4445

CMD ["sh", "-c", "npm run db-migrate-deploy && node dist/apps/tadil-mobile-api/main.js"]

